language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
before_script:
  - "npm i -g gatsby"
  - "npm i"
jobs: 
  include:
    - stage: test
      script: "npm run test"
    - stage: deploy
      github-token: GITHUB_TOKEN
      skip_cleanup: true
      script: "npm run deploy"
stages: 
  - test
  - name: deploy
    if: (branch = master) AND (NOT (type IN (push, pull_request)))
